/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "servicios_jd.h"


void
jefe_departamento_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	usuario_jd  registrar_usuario_jd_1_arg;
	char * *result_2;
	anteproyecto_jd  registrar_anteproyecto_jd_1_arg;
	char * *result_3;
	evaluadores_jd  asignar_evaluadores_jd_1_arg;
	anteproyecto_completo_jd  *result_4;
	char * buscar_anteproyecto_jd_1_arg;
	char * *result_5;
	datos_concepto_jd  modificar_concepto_anteproyecto_jd_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, jefe_departamento, jefe_departamento_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = registrar_usuario_jd_1(&registrar_usuario_jd_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = registrar_anteproyecto_jd_1(&registrar_anteproyecto_jd_1_arg, clnt);
	if (result_2 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_3 = asignar_evaluadores_jd_1(&asignar_evaluadores_jd_1_arg, clnt);
	if (result_3 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_4 = buscar_anteproyecto_jd_1(&buscar_anteproyecto_jd_1_arg, clnt);
	if (result_4 == (anteproyecto_completo_jd *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_5 = modificar_concepto_anteproyecto_jd_1(&modificar_concepto_anteproyecto_jd_1_arg, clnt);
	if (result_5 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	jefe_departamento_1 (host);
exit (0);
}
