/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVICIOS_JD_H_RPCGEN
#define _SERVICIOS_JD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXCODA_jd 3
#define MAXDAG_jd 10
#define MAXMOD_jd 12
#define MAXCONC_jd 20
#define MAXNOM_jd 30
#define MAXCON_jd 30
#define MAXTIT_jd 40

struct usuario_jd {
	char identificacion[MAXDAG_jd];
	char nombre_apellido[MAXNOM_jd];
	char nom_user[MAXDAG_jd];
	char contrasenia[MAXDAG_jd];
	int tipo_user;
};
typedef struct usuario_jd usuario_jd;

struct anteproyecto_jd {
	char modalidad[MAXMOD_jd];
	char titulo[MAXTIT_jd];
	char codigo[MAXCODA_jd];
	char nombre_estud1[MAXNOM_jd];
	char nombre_estud2[MAXNOM_jd];
	char director[MAXNOM_jd];
	char co_director[MAXNOM_jd];
	char fecha_registro[MAXDAG_jd];
	char fecha_aprobacion[MAXDAG_jd];
	int concepto;
	int estado;
	int numero_revision;
};
typedef struct anteproyecto_jd anteproyecto_jd;

struct evaluadores_jd {
	char codigo_anteproyecto[MAXMOD_jd];
	char nombre_evaluador1[MAXNOM_jd];
	char concepto_evaluador1[MAXCONC_jd];
	char fecha_revision1[MAXDAG_jd];
	char nombre_evaluador2[MAXNOM_jd];
	char concepto_evaluador2[MAXCON_jd];
	char fecha_revision2[MAXDAG_jd];
};
typedef struct evaluadores_jd evaluadores_jd;

struct anteproyecto_completo_jd {
	char modalidad[MAXMOD_jd];
	char titulo[MAXTIT_jd];
	char codigo[MAXCODA_jd];
	char nombre_estud1[MAXNOM_jd];
	char nombre_estud2[MAXNOM_jd];
	char director[MAXNOM_jd];
	char co_director[MAXNOM_jd];
	char fecha_registro[MAXDAG_jd];
	char fecha_aprobacion[MAXDAG_jd];
	int concepto;
	int estado;
	int numero_revision;
	char codigo_anteproyecto[MAXMOD_jd];
	char nombre_evaluador1[MAXNOM_jd];
	char concepto_evaluador1[MAXCONC_jd];
	char fecha_revision1[MAXDAG_jd];
	char nombre_evaluador2[MAXNOM_jd];
	char concepto_evaluador2[MAXCON_jd];
	char fecha_revision2[MAXDAG_jd];
};
typedef struct anteproyecto_completo_jd anteproyecto_completo_jd;

struct datos_concepto_jd {
	char codigo_proyecto[MAXCODA_jd];
	char concepto[MAXCONC_jd];
};
typedef struct datos_concepto_jd datos_concepto_jd;

#define jefe_departamento 0x20000002
#define jefe_departamento_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define registrar_usuario_jd 1
extern  char ** registrar_usuario_jd_1(usuario_jd *, CLIENT *);
extern  char ** registrar_usuario_jd_1_svc(usuario_jd *, struct svc_req *);
#define registrar_anteproyecto_jd 2
extern  char ** registrar_anteproyecto_jd_1(anteproyecto_jd *, CLIENT *);
extern  char ** registrar_anteproyecto_jd_1_svc(anteproyecto_jd *, struct svc_req *);
#define asignar_evaluadores_jd 3
extern  char ** asignar_evaluadores_jd_1(evaluadores_jd *, CLIENT *);
extern  char ** asignar_evaluadores_jd_1_svc(evaluadores_jd *, struct svc_req *);
#define buscar_anteproyecto_jd 4
extern  anteproyecto_completo_jd * buscar_anteproyecto_jd_1(char **, CLIENT *);
extern  anteproyecto_completo_jd * buscar_anteproyecto_jd_1_svc(char **, struct svc_req *);
#define modificar_concepto_anteproyecto_jd 5
extern  char ** modificar_concepto_anteproyecto_jd_1(datos_concepto_jd *, CLIENT *);
extern  char ** modificar_concepto_anteproyecto_jd_1_svc(datos_concepto_jd *, struct svc_req *);
extern int jefe_departamento_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define registrar_usuario_jd 1
extern  char ** registrar_usuario_jd_1();
extern  char ** registrar_usuario_jd_1_svc();
#define registrar_anteproyecto_jd 2
extern  char ** registrar_anteproyecto_jd_1();
extern  char ** registrar_anteproyecto_jd_1_svc();
#define asignar_evaluadores_jd 3
extern  char ** asignar_evaluadores_jd_1();
extern  char ** asignar_evaluadores_jd_1_svc();
#define buscar_anteproyecto_jd 4
extern  anteproyecto_completo_jd * buscar_anteproyecto_jd_1();
extern  anteproyecto_completo_jd * buscar_anteproyecto_jd_1_svc();
#define modificar_concepto_anteproyecto_jd 5
extern  char ** modificar_concepto_anteproyecto_jd_1();
extern  char ** modificar_concepto_anteproyecto_jd_1_svc();
extern int jefe_departamento_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_usuario_jd (XDR *, usuario_jd*);
extern  bool_t xdr_anteproyecto_jd (XDR *, anteproyecto_jd*);
extern  bool_t xdr_evaluadores_jd (XDR *, evaluadores_jd*);
extern  bool_t xdr_anteproyecto_completo_jd (XDR *, anteproyecto_completo_jd*);
extern  bool_t xdr_datos_concepto_jd (XDR *, datos_concepto_jd*);

#else /* K&R C */
extern bool_t xdr_usuario_jd ();
extern bool_t xdr_anteproyecto_jd ();
extern bool_t xdr_evaluadores_jd ();
extern bool_t xdr_anteproyecto_completo_jd ();
extern bool_t xdr_datos_concepto_jd ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVICIOS_JD_H_RPCGEN */
