/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "servicios_jd.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
jefe_departamento_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		usuario_jd registrar_usuario_jd_1_arg;
		anteproyecto_jd registrar_anteproyecto_jd_1_arg;
		evaluadores_jd asignar_evaluadores_jd_1_arg;
		char *buscar_anteproyecto_jd_1_arg;
		datos_concepto_jd modificar_concepto_anteproyecto_jd_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case registrar_usuario_jd:
		_xdr_argument = (xdrproc_t) xdr_usuario_jd;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) registrar_usuario_jd_1_svc;
		break;

	case registrar_anteproyecto_jd:
		_xdr_argument = (xdrproc_t) xdr_anteproyecto_jd;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) registrar_anteproyecto_jd_1_svc;
		break;

	case asignar_evaluadores_jd:
		_xdr_argument = (xdrproc_t) xdr_evaluadores_jd;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) asignar_evaluadores_jd_1_svc;
		break;

	case buscar_anteproyecto_jd:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_anteproyecto_completo_jd;
		local = (char *(*)(char *, struct svc_req *)) buscar_anteproyecto_jd_1_svc;
		break;

	case modificar_concepto_anteproyecto_jd:
		_xdr_argument = (xdrproc_t) xdr_datos_concepto_jd;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) modificar_concepto_anteproyecto_jd_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (jefe_departamento, jefe_departamento_version);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, jefe_departamento, jefe_departamento_version, jefe_departamento_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (jefe_departamento, jefe_departamento_version, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, jefe_departamento, jefe_departamento_version, jefe_departamento_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (jefe_departamento, jefe_departamento_version, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
