/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "servicios_jd.h"

bool_t
xdr_usuario_jd (XDR *xdrs, usuario_jd *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->identificacion, MAXDAG_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombre_apellido, MAXNOM_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nom_user, MAXDAG_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->contrasenia, MAXDAG_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->tipo_user))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_anteproyecto_jd (XDR *xdrs, anteproyecto_jd *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->modalidad, MAXMOD_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->titulo, MAXTIT_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->codigo, MAXCODA_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombre_estud1, MAXNOM_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombre_estud2, MAXNOM_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->director, MAXNOM_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->co_director, MAXNOM_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fecha_registro, MAXDAG_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fecha_aprobacion, MAXDAG_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->concepto))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->estado))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numero_revision))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_evaluadores_jd (XDR *xdrs, evaluadores_jd *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->codigo_anteproyecto, MAXMOD_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombre_evaluador1, MAXNOM_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->concepto_evaluador1, MAXCONC_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fecha_revision1, MAXDAG_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombre_evaluador2, MAXNOM_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->concepto_evaluador2, MAXCON_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fecha_revision2, MAXDAG_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_anteproyecto_completo_jd (XDR *xdrs, anteproyecto_completo_jd *objp)
{
	register int32_t *buf;

	int i;

	if (xdrs->x_op == XDR_ENCODE) {
		 if (!xdr_vector (xdrs, (char *)objp->modalidad, MAXMOD_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->titulo, MAXTIT_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->codigo, MAXCODA_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->nombre_estud1, MAXNOM_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->nombre_estud2, MAXNOM_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->director, MAXNOM_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->co_director, MAXNOM_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->fecha_registro, MAXDAG_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->fecha_aprobacion, MAXDAG_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->concepto))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->estado))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->numero_revision))
				 return FALSE;

		} else {
		IXDR_PUT_LONG(buf, objp->concepto);
		IXDR_PUT_LONG(buf, objp->estado);
		IXDR_PUT_LONG(buf, objp->numero_revision);
		}
		 if (!xdr_vector (xdrs, (char *)objp->codigo_anteproyecto, MAXMOD_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->nombre_evaluador1, MAXNOM_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->concepto_evaluador1, MAXCONC_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->fecha_revision1, MAXDAG_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->nombre_evaluador2, MAXNOM_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->concepto_evaluador2, MAXCON_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->fecha_revision2, MAXDAG_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		 if (!xdr_vector (xdrs, (char *)objp->modalidad, MAXMOD_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->titulo, MAXTIT_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->codigo, MAXCODA_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->nombre_estud1, MAXNOM_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->nombre_estud2, MAXNOM_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->director, MAXNOM_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->co_director, MAXNOM_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->fecha_registro, MAXDAG_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->fecha_aprobacion, MAXDAG_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		buf = XDR_INLINE (xdrs, 3 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->concepto))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->estado))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->numero_revision))
				 return FALSE;

		} else {
		objp->concepto = IXDR_GET_LONG(buf);
		objp->estado = IXDR_GET_LONG(buf);
		objp->numero_revision = IXDR_GET_LONG(buf);
		}
		 if (!xdr_vector (xdrs, (char *)objp->codigo_anteproyecto, MAXMOD_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->nombre_evaluador1, MAXNOM_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->concepto_evaluador1, MAXCONC_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->fecha_revision1, MAXDAG_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->nombre_evaluador2, MAXNOM_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->concepto_evaluador2, MAXCON_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
		 if (!xdr_vector (xdrs, (char *)objp->fecha_revision2, MAXDAG_jd,
			sizeof (char), (xdrproc_t) xdr_char))
			 return FALSE;
	 return TRUE;
	}

	 if (!xdr_vector (xdrs, (char *)objp->modalidad, MAXMOD_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->titulo, MAXTIT_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->codigo, MAXCODA_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombre_estud1, MAXNOM_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombre_estud2, MAXNOM_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->director, MAXNOM_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->co_director, MAXNOM_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fecha_registro, MAXDAG_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fecha_aprobacion, MAXDAG_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->concepto))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->estado))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numero_revision))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->codigo_anteproyecto, MAXMOD_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombre_evaluador1, MAXNOM_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->concepto_evaluador1, MAXCONC_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fecha_revision1, MAXDAG_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombre_evaluador2, MAXNOM_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->concepto_evaluador2, MAXCON_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fecha_revision2, MAXDAG_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_datos_concepto_jd (XDR *xdrs, datos_concepto_jd *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->codigo_proyecto, MAXCODA_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->concepto, MAXCONC_jd,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}
