/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "servicios_jd.h"

char **
registrar_usuario_jd_1_svc(usuario_jd *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
registrar_anteproyecto_jd_1_svc(anteproyecto_jd *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
asignar_evaluadores_jd_1_svc(evaluadores_jd *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}

anteproyecto_completo_jd *
buscar_anteproyecto_jd_1_svc(char **argp, struct svc_req *rqstp)
{
	static anteproyecto_completo_jd  result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
modificar_concepto_anteproyecto_jd_1_svc(datos_concepto_jd *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}
