/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "servicios_ed.h"
#include "./librerias/std_ed.h"

anteproyecto_ed *
buscar_anteproyecto_ed_1_svc(char **argp, struct svc_req *rqstp)
{
	static anteproyecto_ed  *result;

	result=(anteproyecto_ed*)malloc(sizeof(anteproyecto_ed));
	
	result = search_draft(*argp, "./informacion/anteproyectos.dat");

	return result;
}

prox_nodo_anteproyecto_ed *
listar_anteproyectos_ed_1_svc(void *argp, struct svc_req *rqstp)
{
	static prox_nodo_anteproyecto_ed  *result;
	
	result=list_draft("./informacion/anteproyectos.dat");

	return result;
}
