/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "servicios_ed.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

anteproyecto_ed *
buscar_anteproyecto_ed_1(char **argp, CLIENT *clnt)
{
	static anteproyecto_ed clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, buscar_anteproyecto_ed,
		(xdrproc_t) xdr_wrapstring, (caddr_t) argp,
		(xdrproc_t) xdr_anteproyecto_ed, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

nodo_anteproyecto_ed *
listar_anteproyectos_ed_1(void *argp, CLIENT *clnt)
{
	static nodo_anteproyecto_ed clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, listar_anteproyectos_ed,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_nodo_anteproyecto_ed, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
