/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "servicios_ed.h"

bool_t
xdr_prox_nodo_anteproyecto_ed (XDR *xdrs, prox_nodo_anteproyecto_ed *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct nodo_anteproyecto_ed), (xdrproc_t) xdr_nodo_anteproyecto_ed))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_anteproyecto_ed (XDR *xdrs, anteproyecto_ed *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->modalidad, MAXMOD_ed,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->titulo, MAXTIT_ed,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->codigo, MAXCODA_ed,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombre_estud1, MAXNOM_ed,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->nombre_estud2, MAXNOM_ed,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->director, MAXNOM_ed,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->co_director, MAXNOM_ed,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fecha_registro, MAXDAG_ed,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fecha_aprobacion, MAXDAG_ed,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->concepto))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->estado))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numero_revision))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nodo_anteproyecto_ed (XDR *xdrs, nodo_anteproyecto_ed *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->titulo, MAXTIT_ed,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->codigo, MAXCODA_ed,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_prox_nodo_anteproyecto_ed (xdrs, &objp->nodo_siguiente))
		 return FALSE;
	return TRUE;
}
