/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "servicio_inicio_sesion.h"

int *
iniciar_sesion_is_1_svc(datos_login_is *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

char **
cabiar_contrasenia_is_1_svc(datos_cambio_contrsenia_is *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return &result;
}
