/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVICIO_INICIO_SESION_H_RPCGEN
#define _SERVICIO_INICIO_SESION_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXPER_is 10

struct datos_login_is {
	char nom_user[MAXPER_is];
	char contrasenia[MAXPER_is];
};
typedef struct datos_login_is datos_login_is;

struct datos_cambio_contrsenia_is {
	char nom_user[MAXPER_is];
	char contrasenia[MAXPER_is];
	char nueva_contrasenia[MAXPER_is];
};
typedef struct datos_cambio_contrsenia_is datos_cambio_contrsenia_is;

#define inicio_sesion 0x20000005
#define inicio_sesion_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define iniciar_sesion_is 1
extern  int * iniciar_sesion_is_1(datos_login_is *, CLIENT *);
extern  int * iniciar_sesion_is_1_svc(datos_login_is *, struct svc_req *);
#define cabiar_contrasenia_is 2
extern  char ** cabiar_contrasenia_is_1(datos_cambio_contrsenia_is *, CLIENT *);
extern  char ** cabiar_contrasenia_is_1_svc(datos_cambio_contrsenia_is *, struct svc_req *);
extern int inicio_sesion_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define iniciar_sesion_is 1
extern  int * iniciar_sesion_is_1();
extern  int * iniciar_sesion_is_1_svc();
#define cabiar_contrasenia_is 2
extern  char ** cabiar_contrasenia_is_1();
extern  char ** cabiar_contrasenia_is_1_svc();
extern int inicio_sesion_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_datos_login_is (XDR *, datos_login_is*);
extern  bool_t xdr_datos_cambio_contrsenia_is (XDR *, datos_cambio_contrsenia_is*);

#else /* K&R C */
extern bool_t xdr_datos_login_is ();
extern bool_t xdr_datos_cambio_contrsenia_is ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVICIO_INICIO_SESION_H_RPCGEN */
