/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "servicios_ed.h"


void
estudiante_director_1(char *host)
{
	CLIENT *clnt;
	anteproyecto_ed  *result_1;
	char * buscar_anteproyecto_ed_1_arg;
	prox_nodo_anteproyecto_ed  *result_2;
	char *listar_anteproyectos_ed_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, estudiante_director, estudiante_director_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = buscar_anteproyecto_ed_1(&buscar_anteproyecto_ed_1_arg, clnt);
	if (result_1 == (anteproyecto_ed *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = listar_anteproyectos_ed_1((void*)&listar_anteproyectos_ed_1_arg, clnt);
	if (result_2 == (prox_nodo_anteproyecto_ed *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	estudiante_director_1 (host);
exit (0);
}
