/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVICIOS_ED_H_RPCGEN
#define _SERVICIOS_ED_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXCODA_ed 3
#define MAXDAG_ed 10
#define MAXMOD_ed 12
#define MAXNOM_ed 30
#define MAXTIT_ed 40

typedef struct nodo_anteproyecto_ed *prox_nodo_anteproyecto_ed;

struct anteproyecto_ed {
	char modalidad[MAXMOD_ed];
	char titulo[MAXTIT_ed];
	char codigo[MAXCODA_ed];
	char nombre_estud1[MAXNOM_ed];
	char nombre_estud2[MAXNOM_ed];
	char director[MAXNOM_ed];
	char co_director[MAXNOM_ed];
	char fecha_registro[MAXDAG_ed];
	char fecha_aprobacion[MAXDAG_ed];
	int concepto;
	int estado;
	int numero_revision;
};
typedef struct anteproyecto_ed anteproyecto_ed;

struct nodo_anteproyecto_ed {
	char titulo[MAXTIT_ed];
	char codigo[MAXCODA_ed];
	prox_nodo_anteproyecto_ed nodo_siguiente;
};
typedef struct nodo_anteproyecto_ed nodo_anteproyecto_ed;

#define estudiante_director 0x20000003
#define estudiante_director_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define buscar_anteproyecto_ed 1
extern  anteproyecto_ed * buscar_anteproyecto_ed_1(char **, CLIENT *);
extern  anteproyecto_ed * buscar_anteproyecto_ed_1_svc(char **, struct svc_req *);
#define listar_anteproyectos_ed 2
extern  nodo_anteproyecto_ed * listar_anteproyectos_ed_1(void *, CLIENT *);
extern  nodo_anteproyecto_ed * listar_anteproyectos_ed_1_svc(void *, struct svc_req *);
extern int estudiante_director_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define buscar_anteproyecto_ed 1
extern  anteproyecto_ed * buscar_anteproyecto_ed_1();
extern  anteproyecto_ed * buscar_anteproyecto_ed_1_svc();
#define listar_anteproyectos_ed 2
extern  nodo_anteproyecto_ed * listar_anteproyectos_ed_1();
extern  nodo_anteproyecto_ed * listar_anteproyectos_ed_1_svc();
extern int estudiante_director_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_prox_nodo_anteproyecto_ed (XDR *, prox_nodo_anteproyecto_ed*);
extern  bool_t xdr_anteproyecto_ed (XDR *, anteproyecto_ed*);
extern  bool_t xdr_nodo_anteproyecto_ed (XDR *, nodo_anteproyecto_ed*);

#else /* K&R C */
extern bool_t xdr_prox_nodo_anteproyecto_ed ();
extern bool_t xdr_anteproyecto_ed ();
extern bool_t xdr_nodo_anteproyecto_ed ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVICIOS_ED_H_RPCGEN */
