/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "./inicio_sesion/servicio_inicio_sesion.h"
#include "./jefe_departamento/servicios_jd.h"
#include "./estudiante_director/servicios_ed.h"
#include "./evaluador/servicios_e.h"

void
prog_servicio(char *host)
{
	
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	prog_servicio(host);
exit (0);
}
