/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "servicio_inicio_sesion.h"


void
inicio_sesion_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	datos_login_is  iniciar_sesion_is_1_arg;
	char * *result_2;
	datos_cambio_contrsenia_is  cabiar_contrasenia_is_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, inicio_sesion, inicio_sesion_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = iniciar_sesion_is_1(&iniciar_sesion_is_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = cabiar_contrasenia_is_1(&cabiar_contrasenia_is_1_arg, clnt);
	if (result_2 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	inicio_sesion_1 (host);
exit (0);
}
