/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "servicios_e.h"


void
evaluador_1(char *host)
{
	CLIENT *clnt;
	char * *result_1;
	datos_concepto_e  ingresar_concepto_anteproyecto_e_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, evaluador, evaluador_version, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = ingresar_concepto_anteproyecto_e_1(&ingresar_concepto_anteproyecto_e_1_arg, clnt);
	if (result_1 == (char **) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	evaluador_1 (host);
exit (0);
}
