/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "servicios_e.h"

bool_t
xdr_datos_concepto_e (XDR *xdrs, datos_concepto_e *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->codigo_proyecto, MAXCODA_e,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->concepto, MAXCONC_e,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->fecha, MAXFEC_e,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->eval_numero))
		 return FALSE;
	return TRUE;
}
