/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVICIOS_E_H_RPCGEN
#define _SERVICIOS_E_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXCODA_e 3
#define MAXCONC_e 20

struct datos_concepto_e {
	char codigo_proyecto[MAXCODA_e];
	char concepto[MAXCONC_e];
};
typedef struct datos_concepto_e datos_concepto_e;

#define evaluador 0x20000004
#define evaluador_version 1

#if defined(__STDC__) || defined(__cplusplus)
#define ingresar_concepto_anteproyecto_e 3
extern  char ** ingresar_concepto_anteproyecto_e_1(datos_concepto_e *, CLIENT *);
extern  char ** ingresar_concepto_anteproyecto_e_1_svc(datos_concepto_e *, struct svc_req *);
extern int evaluador_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ingresar_concepto_anteproyecto_e 3
extern  char ** ingresar_concepto_anteproyecto_e_1();
extern  char ** ingresar_concepto_anteproyecto_e_1_svc();
extern int evaluador_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_datos_concepto_e (XDR *, datos_concepto_e*);

#else /* K&R C */
extern bool_t xdr_datos_concepto_e ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVICIOS_E_H_RPCGEN */
